name = "PurlinLine"
uuid = "720b0b74-7d22-47cf-9c9b-19f6078eb386"
authors = ["Cris Moen <cris.moen@runtosolve.com>"]
version = "0.1.0"

[deps]
NumericalIntegration = "e7bfaba1-d571-5449-8927-abc22e82249b"
StructuresKit = "f6c18a9d-8941-4a0a-88a3-c5fc4dcc4715"
